sentry:
  organization: sentry
  project: zeus
  repository: getsentry/zeus

kubernetes:
  credentials:
    kind: gcloud
    project: zeus-176020
    cluster: zeus
    zone: us-central1-b

steps:
- kind: KubernetesDeployment
  selector:
    label_selector: app in (web, pubsub)
  containers:
  - image: gcr.io/zeus-176020/zeus:{sha}
    name: zeus
- kind: KubernetesStatefulSet
  selector:
    label_selector: app in (vcs-server, worker)
  containers:
  - image: gcr.io/zeus-176020/zeus:{sha}
    name: zeus
