steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/zeus']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'gcr.io/$PROJECT_ID/zeus:latest',
    '--build-arg', 'BUILD_REVISION=$COMMIT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/zeus:$COMMIT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/zeus:latest',
    '.'
  ]
  timeout: 1200s
images:
- 'gcr.io/$PROJECT_ID/zeus:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/zeus:latest'
