apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  nfs:
    path: /
    server: nfs-server.default.svc.cluster.local
